sudo: false
language: python
python:
  - "3.5"
env:
    - TESTENV=py27-django18
    - TESTENV=py34-django18
    - TESTENV=py35-django19

before_install:
    - pip3 install tox

script: tox -e $TESTENV

notifications:
  email: false
  irc: false
